### PR TITLE
IsInterpolatedAt() to enable checking to see if a given value is within the points array

### PR DESCRIPTION
**Pull request by chmorgan**
@sgreben I looked at creating a IsInRange like function but the effort to determine if the value is in the range is nearly the same operation as finding the value and it seemed wasteful to duplicate most of the At() function. I decided to preserve the At() function and insert an extended version, poorly but perhaps sufficiently named AtExtended() method.

Thoughts?

### CODE REVIEW

**Comment by sgreben** [comment]
Hey, sorry about the delay! I'm not sure I understand the problem -- since `X` is assumed to be sorted, we only need to check against its two bounds, right? Like this:

```go
func (f Function) IsInterpolatedAt(x float64) bool {
	n := len(f.X)
	if n == 0 {
		return false
	}
	left, right := f.X[0], f.X[n-1]
	return x >= left && x <= right
}
```

**Comment by chmorgan** [comment]
@sgreben is it that simple? I was under the impression it was more complex. :-)

If so I can refactor to use that instead. Should we make use of that function in the start of the At() function or keep the At() function as it is?

**Comment by sgreben** [comment]
Yeah! Refactoring `At` is a good idea, I'd be happy if you did that :) But if you don't have time I can also do this in a later PR.

**Comment by chmorgan** [comment]
@sgreben first pass at the updated approach

**Comment by sgreben** [comment]
LGTM! should I merge or were you going to refactor `At` as well?

**Comment by chmorgan** [comment]
I’m still planning to use piecewiselinear in some code so I could look at
it again then if you wanted to merge now.

If we did make use of it I wonder if we could introduce issues by removing
the inline checks and using a protection call to the new function. I guess
it’s probably safe enough to do so.

**Pull request merged**
